### ISSUE TITLE
Feedback & Comments

### ISSUE THREAD

**Issue by aidanbell** [jermzblake/CoronaCafeteria#1]
Well done on this project, Jermaine. Here are my comments and feedback:
1. Get specific with your Mongoose Queries! In your delete methods for comments and menu, you're just using `Model.find()`, which will return an array of matching database objects. In these methods, if you're expecting to just be receiving one document back, use the method `Model.findOne()`. This will help your code be a bit more stable, and you won't have to write funky javascript like this: 
https://github.com/jermzblake/CoronaCafeteria/blob/33a2d2831ef3382835439bcb64226b814910487e/controllers/comments.js#L20-L23
2. Avoid calling req.user.save. This works because of how we set up our passport serialize/deserialize user functions, and because of the specific ORM (Mongoose) and DB (MongoDB) that we're using. This is not a guarantee!!! The best practice is to use what we stored in the request object to look up the corresponding database object. In our passport methods, we are attaching an instance of that specific user model to our request object, so we can still access its methods. This won't be a given! A lot of times, we'll just attach a user id to the request object, to make it a little bit more lightweight (imagine the information that would be on a user model of say, a bank. We don't want to be sending that much data with each request).

Aside from that, everything looks good man. Your code formatting is real clean, and everything is nice and legible. 

Great work on this project, and if you have any questions, or need any clarification on what I wrote here, hit me up on Slack!

**Comment by jermzblake** [comment]
Thanks for the feedback and comments, Aiden! I have refactored my code to match your suggestions. This way, like you said, my code is more in line with best practices.
